@server = http://172.10.5.127:443

Get {{server}}/share
###

Get {{server}}/share/getGroupPost/group2

###
POST {{server}}/share
Content-Type: application/json


{
    "post_title": "fisdfrsts Post",
    "post_group": "group2",
    "post_detail": "blahblah",
    "post_img": "image1.jpg",
    "post_writer": "John Doe",
    "like_count": 10,
    "like_users": ["user1", "user2", "user3"],
    "comments": [
    ]

}

###
GET {{server}}/share/getPost/64ae1f5f122f6c2483c76030


###
DELETE {{server}}/share/delete/64ae14a6ef30de34d9f57eb0

###

PUT {{server}}/share/postLike/64ae1f5f122f6c2483c76030
Content-Type: application/json

{
  "likeUser": "John"
}

###

PUT {{server}}/share/update/64ae1f5f122f6c2483c76030
Content-Type: application/json

{
    "post_title": "updated Post",
    "post_group": "group2",
    "post_detail": "blahblah",
    "post_img": "image1.jpg",
    "post_writer": "John Doe",
    "like_count": 10,
    "like_users": ["user1", "user2", "user3"],
    "comments": [
    ]

}

### Create a new comment ###
POST {{server}}/share/postComment/64ae26ed360246d145da7366
Content-Type: application/json

{
  "comments": [
    {
      "comment_detail": "This is a new comment.",
      "comment_writer": "John"
    }
  ]
}