@server = http://172.10.5.127:443

Get {{server}}/share
###

Get {{server}}/share/getGroupPost/group1

###
POST {{server}}/share
Content-Type: application/json


{
    "post_title": "third Post",
    "post_group": "group2",
    "post_detail": "blahblah",
    "post_img": "image1.jpg",
    "post_writer": "John Doe",
    "like_count": 10,
    "like_users": ["user1", "user2", "user3"],
    "comments": [
    ]

}

###
GET {{server}}/share/getPost/64ae14a6ef30de34d9f57eb0


###
DELETE {{server}}/share/delete/64ae14a6ef30de34d9f57eb0

###

PUT {{server}}/share/postLike/64ae14bcef30de34d9f57ec0
Content-Type: application/json

{
  "likeUser": "John"
}


### Create a new comment ###
POST {{server}}/share/postComment/1
Content-Type: application/json

{
  "comment_id": 1,
  "comment_detail": "This is a new comment.",
  "comment_writer": "John"
}