@server = http://172.10.5.127:443

Get {{server}}/signup

###
POST {{server}}/signup
Content-Type: application/json


{
    "userid" : "test2",
    "pw" : "test23pw1"
}

###
GET {{server}}/signup/getUser/hgrhrhuy


###
DELETE {{server}}/signup/delete/sdfsdfsasssssss

###
PUT {{server}}/signup/update/64abae7c461f2e2edcbce488
Content-Type: application/json

{
    "userid": "tehgfhgfhgstid2",
    "pw" : "testpw2222222"
}

###
POST {{server}}/signup/login
Content-Type: application/json

{
    "userid": "abc",
    "pw" : "sd"
}
###

PUT {{server}}/signup/joinGroup/test1
Content-Type: application/json

{
  "groupname": "group2"
}

###
DELETE {{server}}/signup/exitGroup/test1/group2
Content-Type: application/json


### Get User Group Profile
GET /signup/getUserGroupProfile/test1/:groupname
Content-Type: application/json