@server = http://172.10.5.127:443

Get {{server}}/signup

###
POST {{server}}/signup
Content-Type: application/json


{
    "userid" : "test1",
    "pw" : "test23pw1"
}

###
GET {{server}}/signup/getUser/hgrhrhuy


###
DELETE {{server}}/signup/delete/sdfsdfsasssssss

###
PUT {{server}}/signup/update/64abae7c461f2e2edcbce488
Content-Type: application/json

{
    "userid": "tehgfhgfhgstid2",
    "pw" : "testpw2222222"
}

###
POST {{server}}/signup/login
Content-Type: application/json

{
    "userid": "abc",
    "pw" : "sd"
}